### ISSUE TITLE
Azure B2C and Angular app (V 11.0)

### ISSUE THREAD

**Issue by Edenred-Sunil** [Azure-Samples/ms-identity-javascript-angular-tutorial#39]
# Issue

> Please provide us with the following information: 

I used the sample app from "ms-identity-javascript-angular-tutorial-main\3-Authorization-II\2-call-api-b2c" for a sample app. Login works fine and I can see the claims info (username, email account) but when I click on "TodoList" button, the app goes into a continuous loop/ redirect. Tried to create custom component with "handleRedirectObservable()" option but still no luck. Any help is appreciated!

## This issue is for the sample
ms-identity-javascript-angular-tutorial-main\ms-identity-javascript-angular-tutorial-main\3-Authorization-II\2-call-api-b2c

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [x] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [x ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

> Running the app locally.

### Any log messages given by the failure

> It logs to console but unable to capture the logs. I can create a video for it , if needed.

### Expected/desired behavior

> I should be able to view the results from backend api.

### Library version

> Angular V 11.0 and backend .net 5.0

### Browser and version

> Chrome, Edge

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@Edenred-Sunil any chance you can share a short video or gif of the behavior, and share your authentication configuration details. I'm wondering if the issue is similar to [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4058) or [this](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/issues/7).

Also, are you working on a Mac or Windows?

**Comment by Edenred-Sunil** [comment]
Thank you for getting back to me. Yes, the issue is similar to the second link you have sent (https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/issues/7). We have just signIn policy and password reset policy defined. Edit profile is disabled and commented out the code for it. Not sure if that info helps.  We are using signIn info in all the places where it expects "signUpSignIn". I think Azure B2C requires to be defined like that (Key  = "signUpSignIn"). Also, we are using Edge and Chrome browsers.

**Comment by derisen** [comment]
Thanks a lot for the @Edenred-Sunil. Weird thing is that other issue occurred only on Safari with MacOS. I'll try to reproduce your issue to debug and get back to you, apologies for inconvenience.

**Comment by Edenred-Sunil** [comment]
Really appreciate your help @derisen. I got it to work. Had to use scopes from a different app registration for API's (Backend) in the the web app code. Looks like MSAL.js checks for them. In SPA apps, web app and web api needs to have different app registrations and use scopes from them respectively. 

**Note**: I got it to work from a WPF (Backend API) earlier with one single scopes from one app registration (WPF and API using same app registration).

**Comment by derisen** [comment]
@Edenred-Sunil Aah, that explains it! So when the app loaded the `TodoList` component, msal tried to acquire a token for it since that route is protected with `MsalGuard`. But because the scope for acquiring an access token for `TodoListAPI` was defective, it got null response (which should have been caught and handled -I'll look into this), then redirected back to the page where you attempted to acquire a token, which triggered `MsalGuard` again, hence the loop. 

You should use separate app registrations for separate apps, I've explained a little [here](https://stackoverflow.com/questions/63402057/using-msal-and-angular-why-would-one-need-two-separate-aad-app-registrations/63404450#63404450) why that's the recommendation.

Let me know if you have any other issues.
